### ISSUE TITLE
Seems we have a duplicate

### ISSUE THREAD

**Issue by Helias** [Datalux/unict-thesis-template#1]
The repository https://github.com/UNICT-DMI/template-tesi-latex seems a duplicate of this one

We could keep track of both under unict-dmi or put some reference link in both to have more options about the thesis template

**Comment by Datalux** [comment]
Hi, maybe it would be better to keep track of this repo under UNICT-DMI for more visibility for students. 
I'll add the link to this repository anyway :)

**Comment by Helias** [comment]
you can "transfer" the repository under UNICT-DMI, check if you have the permissions to do it, otherwise I'll grant it

**Comment by Datalux** [comment]
I forked the repository in UNICT-DMI :)
